spring:
  application:
    name: careermate
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:MyPostgresDB}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update      # hoặc validate/create theo nhu cầu
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 60 # in second
  refreshable-duration: 604800 # in second
  # in seconds

vnpay:
  tmn-code: 8440W281
  secret-key: G6L03E0MNR9F06OVL2FOA5LGUM69CZZD
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
  return-url: "http://localhost:8080/payment/return"